"""
Project Ontology Manager

This module provides utilities for working with the project ontology,
including loading, validation, and ISA-JSON to RDF conversion.
"""

import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, cast

from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import OWL, RDF, RDFS, XSD

from utils.config_loader import get_profile  # noqa: E402

logger = logging.getLogger(__name__)


def _get_project_namespace() -> Namespace:
    """Return the project ontology namespace from the active profile."""
    return Namespace(get_profile().get_namespace())


# Project ontology namespace (loaded from profile)
PROJECT_NS = _get_project_namespace()
PMD = Namespace("https://w3id.org/pmd/co/")
OBI = Namespace("http://purl.obolibrary.org/obo/")
UO = Namespace("http://purl.obolibrary.org/obo/UO_")
CHEBI = Namespace("http://purl.obolibrary.org/obo/CHEBI_")
NCBIT = Namespace("http://purl.obolibrary.org/obo/NCBITaxon_")
SKOS = Namespace("http://www.w3.org/2004/02/skos/core#")
RO = Namespace("http://purl.obolibrary.org/obo/RO_")


class OntologyManager:
    """Manager for project ontology operations."""

    def __init__(self, base_path: Optional[Path] = None, offline_mode: bool = False):
        """
        Initialize the ontology manager.

        Args:
            base_path: Base path for ontology files. Defaults to project ontologies/ directory.
            offline_mode: If True, skip any network operations.
        """
        if base_path is None:
            base_path = Path(__file__).parent.parent / "ontologies"
        else:
            base_path = Path(base_path)

        self.base_path = base_path
        self.offline_mode = offline_mode

        # Generated ontology files (from scripts/generate_ontology.py)
        ontology_files = get_profile().get_ontology_filenames()
        self.main_ontology = base_path / Path(ontology_files["main_owl"]).name
        self.main_ontology_ttl = base_path / Path(ontology_files["main_ttl"]).name
        self.mapping_file = base_path / "mappings" / "isa_to_rdf_mapping.json"

        # Verification report (from scripts/verify_ontology_refs.py)
        self.verification_report_path = base_path / "validation_report.json"

        self.graph = Graph()
        self.mapping = self._load_mapping()
        self._verification_report: Optional[Dict[str, Any]] = None
        self._verified_uris: Optional[set] = None

        # Track parsing errors for reporting
        self._parse_errors: List[str] = []

    def _load_mapping(self) -> Dict[str, Any]:
        """Load ISA-JSON to RDF mapping configuration."""
        if self.mapping_file.exists():
            with open(self.mapping_file, "r", encoding="utf-8") as f:
                return cast(Dict[str, Any], json.load(f))
        return {}

    def load_ontology(self) -> Graph:
        """
        Load the complete project ontology from generated files.

        Returns:
            RDFLib Graph containing the ontology.
        """
        self.graph = Graph()
        loaded = False

        # Try generated ontology (Turtle preferred for readability)
        for gen_file in [self.main_ontology_ttl, self.main_ontology]:
            if gen_file.exists():
                try:
                    fmt = "turtle" if gen_file.suffix == ".ttl" else "xml"
                    self.graph.parse(str(gen_file), format=fmt)
                    logger.info(
                        f"Loaded generated ontology: {gen_file} ({len(self.graph)} triples)"
                    )
                    loaded = True
                    break
                except Exception as e:
                    logger.warning(f"Could not parse {gen_file}: {e}", exc_info=True)
                    self._parse_errors.append(str(e))

        if not loaded:
            logger.warning("No ontology files found. Ontology graph is empty.")

        return self.graph

    def load_verification_report(self) -> Dict[str, Any]:
        """
        Load the ontology verification report generated by verify_ontology_refs.py.

        Returns:
            Dict with verification results, or empty dict if report not found.
        """
        if self._verification_report is not None:
            return self._verification_report

        if self.verification_report_path.exists():
            try:
                with open(self.verification_report_path, "r", encoding="utf-8") as f:
                    self._verification_report = json.load(f)
                    # Build verified URI set for fast lookup
                    self._verified_uris = {
                        ref["termAccession"]
                        for ref in self._verification_report.get("verified", [])
                        if ref.get("termAccession")
                    }
                    return self._verification_report
            except (json.JSONDecodeError, IOError) as e:
                logger.warning(f"Could not load verification report: {e}")

        self._verification_report = {}
        self._verified_uris = set()
        return self._verification_report

    def is_uri_verified(self, uri: str) -> bool:
        """
        Check if a given URI has been verified against its source ontology.

        Args:
            uri: The ontology URI to check.

        Returns:
            True if the URI was verified, False if not or if report is unavailable.
        """
        if self._verified_uris is None:
            self.load_verification_report()
        return uri in (self._verified_uris or set())

    def get_verified_uris(self) -> Set[str]:
        """
        Get the set of all verified URIs from the verification report.

        Returns:
            Set of verified URI strings.
        """
        if self._verified_uris is None:
            self.load_verification_report()
        return self._verified_uris or set()

    def get_verification_summary(self) -> Dict[str, int]:
        """
        Get a summary of the verification report.

        Returns:
            Dict with counts: total_references, verified, unverified,
            missing_accession, errors.
        """
        report = self.load_verification_report()
        return cast(
            Dict[str, int],
            report.get(
                "summary",
                {
                    "total_references": 0,
                    "verified": 0,
                    "unverified": 0,
                    "missing_accession": 0,
                    "errors": 0,
                },
            ),
        )

    def get_available_ontologies(self) -> List[str]:
        """
        Get list of available ontology files.

        Returns:
            List of available ontology file names
        """
        available = []
        ontology_files = [
            self.main_ontology,
            self.main_ontology_ttl,
        ]

        for ont_file in ontology_files:
            if ont_file.exists():
                available.append(ont_file.name)

        return available

    def validate_ontology(self) -> Dict[str, Any]:
        """
        Validate the loaded ontology for consistency.

        Checks:
        1. Class count and structure
        2. Parsing errors from file loading
        3. Cross-check against verification report (unverified references)

        Returns:
            Dictionary with validation results:
            - 'errors': List of error messages
            - 'warnings': List of warning messages
            - 'has_errors': Boolean indicating if any errors found
        """
        results: Dict[str, Any] = {"errors": [], "warnings": [], "has_errors": False}

        # Check if classes are properly defined
        classes = list(self.graph.subjects(RDF.type, OWL.Class))
        if len(classes) < 10:
            results["warnings"].append(f"Only {len(classes)} classes defined in ontology")

        # Check for orphan classes (no subclasses)
        for cls in classes:
            subclasses = list(self.graph.subjects(RDFS.subClassOf, cls))
            if len(subclasses) == 0 and not str(cls).startswith("http://purl.obolibrary.org"):
                results["warnings"].append(f"Class {cls} has no subclasses")

        # Check for parsing errors
        for error in self._parse_errors:
            results["errors"].append(f"Ontology parsing error: {error}")
            results["has_errors"] = True

        # Cross-check with verification report
        report = self.load_verification_report()
        if report:
            summary = report.get("summary", {})
            unverified_count = summary.get("unverified", 0)
            if unverified_count > 0:
                results["warnings"].append(
                    f"Verification report: {unverified_count} ontology references "
                    f"could not be verified against source ontologies"
                )
            error_count = summary.get("errors", 0)
            if error_count > 0:
                results["warnings"].append(
                    f"Verification report: {error_count} references have errors "
                    f"(unknown termSource, prefix mismatch, etc.)"
                )

        return results

    def get_class_uri(self, class_name: str) -> Optional[URIRef]:
        """
        Get the full URI for a class name from the ontology.

        Args:
            class_name: Name of the class (e.g., "ClearColiCompetentCells")

        Returns:
            URIRef for the class, or None if not found.
        """
        uri = PROJECT_NS[class_name]
        if (uri, None, None) in self.graph:
            return uri
        return None

    def isa_json_to_rdf(self, isa_json: Dict[str, Any]) -> Graph:
        """
        Convert ISA-JSON data to RDF using the ontology.

        Args:
            isa_json: ISA-JSON data as a Python dictionary.

        Returns:
            RDFLib Graph with converted data.
        """
        output_graph = Graph()

        # Add namespace bindings
        ns_prefix = get_profile().get_namespace_prefix() or "onto"
        output_graph.bind(ns_prefix, PROJECT_NS)
        output_graph.bind("co", PMD)
        output_graph.bind("obo", OBI)
        output_graph.bind("uo", UO)

        # Convert investigation metadata
        if "investigation" in isa_json:
            self._convert_investigation(output_graph, isa_json["investigation"])

        # Convert studies
        if "studies" in isa_json:
            for study in isa_json["studies"]:
                self._convert_study(output_graph, study)

        return output_graph

    def _convert_investigation(self, graph: Graph, investigation: Dict[str, Any]):
        """Convert investigation metadata to RDF."""
        inv_id = investigation.get("@id", "")
        inv_iri = URIRef(inv_id) if inv_id else PROJECT_NS["investigation"]

        graph.add((inv_iri, RDF.type, PROJECT_NS["Investigation"]))

        if "title" in investigation:
            graph.add((inv_iri, RDFS.label, Literal(investigation["title"])))

        if "description" in investigation:
            graph.add((inv_iri, RDFS.comment, Literal(investigation["description"])))

    def _convert_study(self, graph: Graph, study: Dict[str, Any]):
        """Convert study data to RDF."""
        study_id = study.get("@id", "")
        study_iri = URIRef(study_id) if study_id else PROJECT_NS["study"]

        graph.add((study_iri, RDF.type, PROJECT_NS["Study"]))

        # Convert materials
        if "materials" in study:
            self._convert_materials(graph, study["materials"])

        # Convert protocols
        if "protocols" in study:
            self._convert_protocols(graph, study["protocols"])

        # Convert assays
        if "assays" in study:
            self._convert_assays(graph, study["assays"])

        # Convert process sequence
        if "processSequence" in study:
            self._convert_process_sequence(graph, study["processSequence"])

    def _convert_materials(self, graph: Graph, materials: Dict[str, Any]):
        """Convert materials to RDF."""
        # Sources
        if "sources" in materials:
            for source in materials["sources"]:
                self._convert_material(graph, source, "Source")

        # Samples
        if "samples" in materials:
            for sample in materials["samples"]:
                self._convert_material(graph, sample, "Sample")

        # Other materials
        if "otherMaterials" in materials:
            for material in materials["otherMaterials"]:
                self._convert_material(graph, material, "OtherMaterial")

    def _convert_material(self, graph: Graph, material: Dict[str, Any], material_type: str):
        """Convert a single material to RDF."""
        mat_id = material.get("@id", "")
        mat_iri = URIRef(mat_id) if mat_id else PROJECT_NS[f"material_{material_type}"]

        graph.add((mat_iri, RDF.type, PROJECT_NS[material_type]))

        if "name" in material:
            graph.add((mat_iri, RDFS.label, Literal(material["name"])))

        # Add derivesFrom relationships
        if "derivesFrom" in material:
            for parent_id in material["derivesFrom"]:
                parent_iri = URIRef(parent_id)
                graph.add((mat_iri, PROJECT_NS["derivesFrom"], parent_iri))

    def _convert_protocols(self, graph: Graph, protocols: List[Dict[str, Any]]):
        """Convert protocols to RDF."""
        for protocol in protocols:
            prot_id = protocol.get("@id", "")
            prot_iri = URIRef(prot_id) if prot_id else PROJECT_NS["protocol"]

            graph.add((prot_iri, RDF.type, PROJECT_NS["Protocol"]))

            if "name" in protocol:
                graph.add((prot_iri, RDFS.label, Literal(protocol["name"])))

            # Map protocol type to ontology class
            if "protocolType" in protocol:
                prot_type = protocol["protocolType"]
                if isinstance(prot_type, dict):
                    type_name = prot_type.get("annotationValue", "")
                    mapped_class = self._map_protocol_type(type_name)
                    if mapped_class:
                        graph.add((prot_iri, RDF.type, mapped_class))

    def _map_protocol_type(self, type_name: str) -> Optional[URIRef]:
        """Map protocol type string to ontology class URI."""
        if "protocolType" in self.mapping:
            if "manufacturing_process" in self.mapping["protocolType"]:
                mapping = self.mapping["protocolType"]["manufacturing_process"].get(
                    "onto_mapping", {}
                )
                return cast(URIRef, mapping.get(type_name))
        return None

    def _convert_assays(self, graph: Graph, assays: List[Dict[str, Any]]):
        """Convert assays to RDF."""
        for assay in assays:
            assay_id = assay.get("@id", "")
            assay_iri = URIRef(assay_id) if assay_id else PROJECT_NS["assay"]

            graph.add((assay_iri, RDF.type, PROJECT_NS["Assay"]))

            if "name" in assay:
                graph.add((assay_iri, RDFS.label, Literal(assay["name"])))

    def _convert_process_sequence(self, graph: Graph, processes: List[Dict[str, Any]]):
        """Convert process sequence to RDF."""
        for process in processes:
            proc_id = process.get("@id", "")
            proc_iri = URIRef(proc_id) if proc_id else PROJECT_NS["process"]

            graph.add((proc_iri, RDF.type, PROJECT_NS["process"]))

            # Add executesProtocol relationship
            if "executesProtocol" in process:
                prot_iri = URIRef(process["executesProtocol"])
                graph.add((proc_iri, PROJECT_NS["executesProtocol"], prot_iri))

            # Add inputs
            if "inputs" in process:
                for input_id in process["inputs"]:
                    input_iri = URIRef(input_id)
                    graph.add((proc_iri, PROJECT_NS["hasInput"], input_iri))

            # Add outputs
            if "outputs" in process:
                for output_id in process["outputs"]:
                    output_iri = URIRef(output_id)
                    graph.add((proc_iri, PROJECT_NS["hasOutput"], output_iri))

    def save_rdf(self, graph: Graph, output_path: str, format: str = "turtle"):
        """
        Save RDF graph to file.

        Args:
            graph: RDFLib Graph to save.
            output_path: Path to output file.
            format: Output format ('turtle', 'xml', 'nt', 'n3').
        """
        graph.serialize(destination=output_path, format=format)
        logger.info(f"RDF graph saved to {output_path}")

    def get_ontology_statistics(self) -> Dict[str, int]:
        """
        Get statistics about the loaded ontology.

        Returns:
            Dictionary with ontology statistics.
        """
        annotation_props = len(list(self.graph.subjects(RDF.type, OWL.AnnotationProperty)))
        return {
            "classes": len(list(self.graph.subjects(RDF.type, OWL.Class))),
            "object_properties": len(list(self.graph.subjects(RDF.type, OWL.ObjectProperty))),
            "datatype_properties": len(list(self.graph.subjects(RDF.type, OWL.DatatypeProperty))),
            "annotation_properties": annotation_props,
            "properties": (
                len(list(self.graph.subjects(RDF.type, OWL.ObjectProperty)))
                + len(list(self.graph.subjects(RDF.type, OWL.DatatypeProperty)))
                + annotation_props
            ),
            "individuals": len(list(self.graph.subjects(RDF.type, OWL.NamedIndividual))),
            "triples": len(self.graph),
        }


def create_sample_individuals() -> Graph:
    """
    Create sample individuals for common materials and parameters.

    Returns:
        RDFLib Graph with sample individuals.
    """
    graph = Graph()
    graph.bind("onto", PROJECT_NS)
    graph.bind("obo", OBI)
    graph.bind("uo", UO)

    # Sample material individuals
    samples = {
        "cells_clearcoli_batchA": {
            "type": PROJECT_NS.ClearColiCompetentCells,
            "label": "ClearColi competent E. coli batch A",
        },
        "dna_plasmid_pVV021": {"type": PROJECT_NS.AssembledDNA, "label": "Plasmid pVV021"},
    }

    # Create individuals
    for sample_id, sample_data in samples.items():
        sample_iri = PROJECT_NS[sample_id]
        graph.add((sample_iri, RDF.type, cast(URIRef, sample_data["type"])))
        graph.add((sample_iri, RDFS.label, Literal(sample_data["label"])))

    # Sample parameter individuals
    parameters = {
        "param_electro_voltage_1200V": {
            "type": PROJECT_NS.ElectroporationVoltage,
            "value": 1200,
            "unit": UO["0000218"],  # volt
        },
        "param_pulse_number_1": {"type": PROJECT_NS.ElectroporationPulseNumber, "value": 1},
    }

    for param_id, param_data in parameters.items():
        param_iri = PROJECT_NS[param_id]
        graph.add((param_iri, RDF.type, cast(URIRef, param_data["type"])))
        graph.add(
            (param_iri, PROJECT_NS["value"], Literal(param_data["value"], datatype=XSD.decimal))
        )
        if "unit" in param_data:
            graph.add((param_iri, PROJECT_NS["hasUnit"], cast(URIRef, param_data["unit"])))

    return graph


if __name__ == "__main__":
    # Setup logging for standalone execution
    logging.basicConfig(level=logging.INFO)

    # Test ontology manager
    manager = OntologyManager()

    logger.info("Loading project ontology...")
    graph = manager.load_ontology()

    logger.info("\nOntology Statistics:")
    stats = manager.get_ontology_statistics()
    for key, value in stats.items():
        logger.info(f"  {key}: {value}")

    logger.info("\nValidating ontology...")
    validation = manager.validate_ontology()
    if validation["errors"]:
        logger.error("Errors:")
        for error in validation["errors"]:
            logger.error(f"  - {error}")
    if validation["warnings"]:
        logger.warning("Warnings:")
        for warning in validation["warnings"]:
            logger.warning(f"  - {warning}")

    if not validation["errors"] and not validation["warnings"]:
        logger.info("Ontology validation passed!")

    # Create sample individuals
    logger.info("\nCreating sample individuals...")
    sample_graph = create_sample_individuals()
    manager.save_rdf(sample_graph, "ontologies/sample_individuals.ttl")
